// Generated by CoffeeScript 1.4.0
var Ui, oldAlert;

window.openLoadDialog = function() {
  return $('#loadModal').modal();
};

window.effectController = {
  gcodeIndex: 10,
  animate: false,
  motionLine: true,
  feedLine: true,
  speed: 0,
  color: [0, 128, 255]
};

oldAlert = window.alert;

window.alert = function() {
  if (window.Android) {
    return Android.showToast(arguments[0]);
  } else {
    return oldAlert.apply(null, arguments);
  }
};

Ui = (function() {
  var defaultImportPath;

  Ui.prototype.controllers = {
    gcodeIndex: null,
    animate: null
  };

  defaultImportPath = 'models/octocat.gcode';

  Ui.prototype.onGcodeLoaded = function(model) {
    this.renderer.onGcodeLoaded(model);
    return $('#loadModal').modal('hide');
  };

  function Ui() {
    console.log('Starting Ui');
    alert('oiem');
    if (!Modernizr.webgl) {
      alert('Sorry, you need a WebGL capable browser to use this.');
      return false;
    }
    if (!Modernizr.localstorage) {
      alert('Man, your browser is ancient. WTF Can\'t work like this!');
      return false;
    }
    this.renderer = new Renderer($('#renderArea')[0], this);
    GCodeImporter.setup(this.onGcodeLoaded.bind(this), defaultImportPath);
    this.setupDatGUI();
  }

  Ui.prototype.setupDatGUI = function() {
    return $('.dg.main').mousedown(function(e) {
      return e.stopPropagation();
    });
  };

  return Ui;

})();

$(function() {
  return window.ui = new Ui;
});
